version: '3.7'

services:
  appweb:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/usr/share/nginx/html
  
  php:
    image: php:apache
    volumes: 
      - .:/var/www/html
    ports:
      - 85:80
      